name: Deploy Standalone HTML

on:
  push:
    branches:
      - main
    paths:
      - 'docs/readme/**'
  workflow_dispatch:


jobs:
  deploy-standalone-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}  # Use PAT instead of GITHUB_TOKEN
          publish_dir: ./docs/readme
          destination_dir: .
          keep_files: true