name: Deploy Standalone HTML
on:
  push:
    branches:
      - main
    paths:
      - 'docs/readme/**'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy-standalone-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: List contents of docs/readme
        run: ls -R docs/readme
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/readme
          destination_dir: .
          keep_files: true