name: Standalone HTML

on:
  push:
    branches:
      - main
    paths:
      - 'static/pca_animation.html'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-standalone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'static'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}